set sdir [file dirname [file normalize $argv0 ] ]
set auto_path [linsert $auto_path 0 $sdir]
package require sftp 1.0
package require coro 1.0

set sftp_password [ argv_password ]
set sftp_user [ argv_user ]
set sftp_host [ argv_host ]
set srcdst [ argv_rest ]

if { [ llength $srcdst ] != 2 } {
    puts stderr "Only accept src dst"
    exit 1
}

log_user 0
sftp_login $sftp_user $sftp_host $sftp_password


sftp_get [lindex 0 $srcdst] [lindex 1 $srcdst]


sftp_logout
